package lol.terabrendon.houseshare2.data.local.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

object Crypto {

    // A Keystore key only works with the block mode and padding it was created with: changing
    // them needs a new alias.
    private const val KEY_ALIAS = "houseshare_aes_gcm"
    private const val KEYSTORE = "AndroidKeyStore"
    private const val ALGORITHM = KeyProperties.KEY_ALGORITHM_AES
    private const val BLOCK_MODE = KeyProperties.BLOCK_MODE_GCM

    // GCM is a stream mode, it has no padding.
    private const val PADDING = KeyProperties.ENCRYPTION_PADDING_NONE
    private const val TRANSFORMATION = "$ALGORITHM/$BLOCK_MODE/$PADDING"

    // The size of the IV generated by the Keystore for GCM, and of the authentication tag.
    private const val IV_LENGTH = 12
    private const val TAG_LENGTH_BITS = 16 * 8

    private val keyStore = KeyStore
        .getInstance(KEYSTORE)
        .apply { load(null) }


    private fun getKey(): SecretKey {
        val existingKey = keyStore
            .getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry

        return existingKey?.secretKey ?: createKey()
    }

    private fun createKey(): SecretKey {
        return KeyGenerator
            // Without the provider the key is generated in software and never stored in the
            // Keystore (and the software generator rejects a KeyGenParameterSpec anyway).
            .getInstance(ALGORITHM, KEYSTORE)
            .apply {
                init(
                    KeyGenParameterSpec
                        .Builder(
                            KEY_ALIAS,
                            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                        )
                        .setBlockModes(BLOCK_MODE)
                        .setEncryptionPaddings(PADDING)
                        .setRandomizedEncryptionRequired(true)
                        // We don't need this extra level of security
                        .setUserAuthenticationRequired(false)
                        .build()
                )
            }
            .generateKey()
    }

    // A Cipher is not thread safe, every call gets its own.
    fun encrypt(bytes: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getKey())
        val iv = cipher.iv
        val encrypted = cipher.doFinal(bytes)
        return iv + encrypted
    }

    fun decrypt(bytes: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val (iv, data) = bytes.splitAt(IV_LENGTH)
        cipher.init(Cipher.DECRYPT_MODE, getKey(), GCMParameterSpec(TAG_LENGTH_BITS, iv))

        return cipher.doFinal(data)
    }

    private fun ByteArray.splitAt(index: Int): Pair<ByteArray, ByteArray> {
        return copyOfRange(0, index) to copyOfRange(index, size)
    }
}
